name: Exécuter le script Python à chaque push

on:
  push:
    branches:
      - main  # Cela signifie que le workflow sera déclenché pour un push sur la branche `main`

jobs:
  run-script:
    runs-on: ubuntu-latest  # Utiliser un runner Ubuntu fourni par GitHub

    steps:
    - name: Vérifier le code
      uses: actions/checkout@v2  # Cette étape permet de récupérer ton code dans le runner GitHub

    - name: Installer pytest
      run: |
        pip install pytest

    - name: Lancer le script Python
      run: |
        python main.py  # Ex

    - name: Exécuter pytest
      run: |
        pytest
